### PR TITLE
Portfolio Accessibility

### PR DESCRIPTION
**Pull request by jovasal**
🆗 Check all of the items listed in the article [Easy Checks – A First Review of Web Accessibility](https://www.w3.org/WAI/test-evaluate/preliminary/) (which you already read in the previous lesson).

🆗 Determine if your Portfolio needs any changes.

🆗 Make changes in a separate branch and open a new pull request.

🆗 Prepare a report listing all points that you have checked, and the result of your evaluation.

🆗 Your report should include Page Titles, Image Text, Text Headings, Color Contrast, Rezise, Interaction, Moving Content, Multimedia, and Basic structure of the page.

🆗 Each point on the list needs to include the result of your evaluation.

### CODE REVIEW

**Comment by jovasal** [comment]
The title was added:

image

Actually, is working:

image

**Comment by jovasal** [comment]
Images were updated with Image Text Alternatives.

image

image

image

image

image

image

**Comment by jovasal** [comment]
Text headings are fine. No need for changes as shown in the following image:

image

**Comment by jovasal** [comment]
Color Contrast is applied successfully:

image

**Comment by jovasal** [comment]
Resize is working:

image
image

**Comment by jovasal** [comment]
Moving content:

The logo is moving around for 1 second:

image

when mouse in the logo:

image

All buttons have different colors when the mouse is inside of them:

image
image

image
image

image
image

**Comment by jovasal** [comment]
Multimedia. This page does not contain multimedia

**Comment by jovasal** [comment]
Basic structure of the page:

Disable all images:

image
image
image
image
image
image
image

all is working fine without images. Nothing was moved.

**Comment by jovasal** [comment]
The form is working fine as agreed with FIGMA version.

image
image
image
image

**Review by Zuhaib042 — CHANGES_REQUESTED** [review]
Hi @jovasal 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✅ Descriptive PR
✅ Professional Readme

## Required Changes ♻️
- [x] Kindly consider changing the `h1` on line 205 in index.html to any other `h` tag because we should only have one h1 tag in each webpage for better semantics and SEO.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jovasal** [comment]
h1 were changed fo h2 in Form (Contact Me):

image

All changes were made

**Comment by jovasal** [comment]
image

Only 1 <h1> tag in this project.

**Review by abdallahmalima — APPROVED** [review]
Hi @jovasal , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Report includes a check about page titles.✔️
- Report includes a check about image text alternatives.✔️
- Report includes a check about text headings.✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._✔️

**Pull request closed without merging**
