### PR TITLE
Portfolio: application deploy

### PR DESCRIPTION
**Pull request by jovasal**
🆗 Deploy your website using GitHub Pages.

🆗 Check the online version of your portfolio and make sure that the page works properly.

🆗 Update the README of your repository to include a link to the online version.

### CODE REVIEW

**Comment by jovasal** [comment]
Linters were passed ok

**Comment by jovasal** [comment]
Linters contain issues yet but are not for this project. Webhint has been failing since a week ago.

@github-actions
Linters / Webhint (pull_request) Failing after 22s

**Comment by jovasal** [comment]
Check the online version of your portfolio and make sure that the page works properly.

https://jovasal.github.io

Is working fine

**Comment by jovasal** [comment]
Update the README of your repository to include a link to the online version.

README and MIT were updated with actual repositories and links

**Review by joskalenda — CHANGES_REQUESTED** [review]
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @jovasal , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
|  |

## Highlights

- [ ].. ✅ Green linters
- [ ].. ✅ App deployed
- [ ].. ✅ Great readme file

## Required Changes ♻️

- [x] The app is well deployed but there is something that I wanted to show you, if possible please fix the change and request another review, you have added some padding to the `projects` container that is affecting the mobile version as well, please check the image below 

YOUR DESIGN




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jovasal** [comment]
Changes were made as recommended by the reviewer @joskalenda.

The padding was changed as per the last recommendation using padding: 1px auto:
image

Under Figma rules, Marging was added for 24px and space in the margin and button:

image


Al changes is working fine.

**Comment by AdnanOlarmmi** [comment]
.

**Review by AdnanOlarmmi — APPROVED** [review]
Hi @jovasal,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Approved office man

## Highlights
- Fixed required changes.
- App is deployed okay.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
